<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 /home/jschill/code/svelte/threlte_test/static/models/C4DSS_V2.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      C: THREE.Mesh
      S: THREE.Mesh
      ['@_1']: THREE.Mesh
      F: THREE.Mesh
      S_1: THREE.Mesh
      U: THREE.Mesh
      J_fracturepart_1: THREE.Mesh
      u_fracturepart2_1: THREE.Mesh
      u_fracturepart3_1: THREE.Mesh
      s_fracturepart2_1: THREE.Mesh
      s_fracturepart5_2: THREE.Mesh
      s_fracturepart5_3: THREE.Mesh
      t_fracturepart2_1: THREE.Mesh
      t_fracturepart5_1: THREE.Mesh
      i_fracturepart2_1: THREE.Mesh
      i_fracturepart5_1: THREE.Mesh
      i_fracturepart_2: THREE.Mesh
      n_fracturepart2_3: THREE.Mesh
      n_fracturepart2_4: THREE.Mesh
      n_fracturepart2_5: THREE.Mesh
      n_fracturepart5_1: THREE.Mesh
      S_fracturepart_1: THREE.Mesh
      c_fracturepart_1: THREE.Mesh
      h_fracturepart3_1: THREE.Mesh
      h_fracturepart4_3: THREE.Mesh
      h_fracturepart4_4: THREE.Mesh
      h_fracturepart4_5: THREE.Mesh
      i_fracturepart3_1: THREE.Mesh
      i_fracturepart4_1: THREE.Mesh
      i_fracturepart_3: THREE.Mesh
      l_fracturepart3_2: THREE.Mesh
      l_fracturepart4_2: THREE.Mesh
      l_fracturepart1_3: THREE.Mesh
      l_fracturepart1_4: THREE.Mesh
      l_fracturepart1_5: THREE.Mesh
      l_fracturepart2_1: THREE.Mesh
      l_fracturepart3_3: THREE.Mesh
      l_fracturepart4_3: THREE.Mesh
      l_fracturepart5_1: THREE.Mesh
      e_fracturepart1_2: THREE.Mesh
      e_fracturepart1_3: THREE.Mesh
      e_fracturepart5_1: THREE.Mesh
      m_fracturepart1_6: THREE.Mesh
      m_fracturepart1_7: THREE.Mesh
      m_fracturepart1_8: THREE.Mesh
      m_fracturepart1_9: THREE.Mesh
      m_fracturepart1_10: THREE.Mesh
      m_fracturepart1_11: THREE.Mesh
      m_fracturepart5_1: THREE.Mesh
      a_fracturepart_1: THREE.Mesh
      n_fracturepart_1: THREE.Mesh
    }
    materials: {
      White: THREE.MeshStandardMaterial
      Green: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/C4DSS_V2.gltf')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[-0.86, -0.6, 0]} rotation={[-0.13, -0.33, 0.16]}>
      <T.Group position={[-2.04, 0, 0]}>
        <T.Group position={[2.36, 0, 0]}>
          <T.Mesh geometry={gltf.nodes.F.geometry} material={gltf.materials.White} />
          <T.Mesh geometry={gltf.nodes.S_1.geometry} material={gltf.materials.White} position={[0.51, 0, 0]} />
          <T.Mesh geometry={gltf.nodes.U.geometry} material={gltf.materials.White} position={[1.05, 0, 0]} />
        </T.Group>
        <T.Mesh geometry={gltf.nodes.C.geometry} material={gltf.materials.White} />
        <T.Mesh geometry={gltf.nodes.S.geometry} material={gltf.materials.White} position={[0.57, 0, 0]} />
        <T.Mesh geometry={gltf.nodes['@_1'].geometry} material={gltf.materials.White} position={[1.29, 0, 0]} />
      </T.Group>
    </T.Group>
    <T.Group position={[-2.42, 1.67, -0.54]} rotation={[0.01, -0.33, 0.16]}>
      <T.Mesh
        geometry={gltf.nodes.u_fracturepart2_1.geometry}
        material={gltf.materials.Green}
        position={[0.81, 0.53, -0.53]}
        rotation={[-0.01, -0.06, -0.06]}
        scale={0.97}
      />
      <T.Mesh
        geometry={gltf.nodes.u_fracturepart3_1.geometry}
        material={gltf.materials.Green}
        position={[0.5, 0.52, -0.46]}
        rotation={[0.06, -0.07, 0.02]}
        scale={0.96}
      />
    </T.Group>
    <T.Group position={[-1.38, 1.84, -0.18]} rotation={[0.01, -0.33, 0.16]}>
      <T.Mesh
        geometry={gltf.nodes.s_fracturepart2_1.geometry}
        material={gltf.materials.Green}
        position={[0.52, 0.57, -0.46]}
        rotation={[0.07, 0.05, 0.02]}
        scale={1.03}
      />
      <T.Mesh
        geometry={gltf.nodes.s_fracturepart5_2.geometry}
        material={gltf.materials.Green}
        position={[0.53, 0.17, -0.36]}
        rotation={[0.07, -0.03, 0.03]}
        scale={0.99}
      />
      <T.Mesh
        geometry={gltf.nodes.s_fracturepart5_3.geometry}
        material={gltf.materials.Green}
        position={[0.62, 0.11, -0.31]}
        rotation={[0, 0.06, 0.07]}
        scale={1.04}
      />
    </T.Group>
    <T.Group position={[-0.58, 1.98, 0.1]} rotation={[0.01, -0.33, 0.16]}>
      <T.Mesh
        geometry={gltf.nodes.t_fracturepart2_1.geometry}
        material={gltf.materials.Green}
        position={[0.43, 0.72, -0.45]}
        rotation={[-0.01, 0.07, 0.03]}
        scale={1.04}
      />
      <T.Mesh
        geometry={gltf.nodes.t_fracturepart5_1.geometry}
        material={gltf.materials.Green}
        position={[0.55, 0.25, -0.41]}
        rotation={[0.03, 0.08, 0.06]}
        scale={1.04}
      />
    </T.Group>
    <T.Group position={[0.13, 2.1, 0.35]} rotation={[0.01, -0.33, 0.16]}>
      <T.Mesh
        geometry={gltf.nodes.i_fracturepart2_1.geometry}
        material={gltf.materials.Green}
        position={[0.35, 0.73, -0.41]}
        rotation={[-0.04, 0.08, 0.08]}
        scale={1.04}
      />
      <T.Mesh
        geometry={gltf.nodes.i_fracturepart5_1.geometry}
        material={gltf.materials.Green}
        position={[0.37, 0.45, -0.55]}
        rotation={[0.06, 0.08, -0.08]}
        scale={1.04}
      />
      <T.Mesh
        geometry={gltf.nodes.i_fracturepart_2.geometry}
        material={gltf.materials.Green}
        position={[0.27, 1.32, -0.41]}
        rotation={[0.03, -0.02, 0.07]}
        scale={0.99}
      />
    </T.Group>
    <T.Group position={[0.63, 2.18, 0.52]} rotation={[0.01, -0.33, 0.16]}>
      <T.Mesh
        geometry={gltf.nodes.n_fracturepart2_3.geometry}
        material={gltf.materials.Green}
        position={[0.54, 1, -0.96]}
        rotation={[0.03, -0.06, -0.07]}
        scale={0.97}
      />
      <T.Mesh
        geometry={gltf.nodes.n_fracturepart2_4.geometry}
        material={gltf.materials.Green}
        position={[0.2, 0.84, -0.51]}
        rotation={[-0.05, -0.06, -0.02]}
        scale={0.97}
      />
      <T.Mesh
        geometry={gltf.nodes.n_fracturepart2_5.geometry}
        material={gltf.materials.Green}
        position={[0.53, 0.97, -0.93]}
        rotation={[-0.01, -0.06, -0.04]}
        scale={0.96}
      />
      <T.Mesh
        geometry={gltf.nodes.n_fracturepart5_1.geometry}
        material={gltf.materials.Green}
        position={[0.6, 0.51, -0.48]}
        rotation={[0.02, 0, 0]}
      />
    </T.Group>
    <T.Group position={[-3.26, -0.01, -0.85]} rotation={[0.01, -0.33, 0.16]}>
      <T.Mesh
        geometry={gltf.nodes.h_fracturepart3_1.geometry}
        material={gltf.materials.Green}
        position={[0.6, 0.65, -0.49]}
        rotation={[0, 0.04, -0.01]}
        scale={1.02}
      />
      <T.Mesh
        geometry={gltf.nodes.h_fracturepart4_3.geometry}
        material={gltf.materials.Green}
        position={[0.9, 0.27, -0.51]}
        rotation={[0.02, 0, -0.03]}
      />
      <T.Mesh
        geometry={gltf.nodes.h_fracturepart4_4.geometry}
        material={gltf.materials.Green}
        position={[0.39, 0.02, -0.18]}
        rotation={[-0.05, 0.05, 0.07]}
        scale={1.03}
      />
      <T.Mesh
        geometry={gltf.nodes.h_fracturepart4_5.geometry}
        material={gltf.materials.Green}
        position={[0.3, 0.02, -0.28]}
        rotation={[-0.06, -0.06, -0.03]}
        scale={0.97}
      />
    </T.Group>
    <T.Group position={[-2.21, 0.17, -0.49]} rotation={[0.01, -0.33, 0.16]}>
      <T.Mesh
        geometry={gltf.nodes.i_fracturepart3_1.geometry}
        material={gltf.materials.Green}
        position={[0.23, 0.66, -0.51]}
        rotation={[0, -0.04, -0.03]}
        scale={0.97}
      />
      <T.Mesh
        geometry={gltf.nodes.i_fracturepart4_1.geometry}
        material={gltf.materials.Green}
        position={[0.24, 0.33, -0.52]}
        rotation={[-0.07, -0.07, -0.05]}
        scale={0.96}
      />
      <T.Mesh
        geometry={gltf.nodes.i_fracturepart_3.geometry}
        material={gltf.materials.Green}
        position={[0.28, 1.35, -0.54]}
        rotation={[0.06, 0, -0.07]}
      />
    </T.Group>
    <T.Group position={[-1.71, 0.25, -0.31]} rotation={[0.01, -0.33, 0.16]}>
      <T.Mesh
        geometry={gltf.nodes.l_fracturepart3_2.geometry}
        material={gltf.materials.Green}
        position={[0.31, 1.03, -0.44]}
        rotation={[0.02, 0.04, 0.04]}
        scale={1.02}
      />
      <T.Mesh
        geometry={gltf.nodes.l_fracturepart4_2.geometry}
        material={gltf.materials.Green}
        position={[0.36, 0.5, -0.48]}
        rotation={[-0.05, -0.01, 0]}
        scale={0.99}
      />
    </T.Group>
    <T.Group position={[-1.19, 0.34, -0.13]} rotation={[0.01, -0.33, 0.16]}>
      <T.Mesh
        geometry={gltf.nodes.l_fracturepart1_3.geometry}
        material={gltf.materials.Green}
        position={[0.61, 0.24, -0.42]}
        rotation={[0.03, 0.07, 0.05]}
        scale={1.04}
      />
      <T.Mesh
        geometry={gltf.nodes.l_fracturepart1_4.geometry}
        material={gltf.materials.Green}
        position={[0.29, 0.73, -0.44]}
        rotation={[0.06, -0.04, -0.02]}
        scale={0.98}
      />
      <T.Mesh
        geometry={gltf.nodes.l_fracturepart1_5.geometry}
        material={gltf.materials.Green}
        position={[0.15, 0.99, -0.14]}
        rotation={[0, 0.04, 0.02]}
        scale={1.02}
      />
      <T.Mesh
        geometry={gltf.nodes.l_fracturepart2_1.geometry}
        material={gltf.materials.Green}
        position={[0.27, 1.43, -0.51]}
        rotation={[0.07, 0.01, 0.01]}
      />
      <T.Mesh
        geometry={gltf.nodes.l_fracturepart3_3.geometry}
        material={gltf.materials.Green}
        position={[0.05, 1.19, -0.68]}
        rotation={[-0.06, -0.08, -0.07]}
        scale={0.96}
      />
      <T.Mesh
        geometry={gltf.nodes.l_fracturepart4_3.geometry}
        material={gltf.materials.Green}
        position={[0.34, 0.36, -0.41]}
        rotation={[-0.07, -0.01, 0.07]}
        scale={0.99}
      />
      <T.Mesh
        geometry={gltf.nodes.l_fracturepart5_1.geometry}
        material={gltf.materials.Green}
        position={[0.28, 0.98, -0.41]}
        rotation={[0.03, -0.01, 0.07]}
        scale={0.99}
      />
    </T.Group>
    <T.Group position={[-0.67, 0.42, 0.04]} rotation={[0.01, -0.33, 0.16]}>
      <T.Mesh
        geometry={gltf.nodes.e_fracturepart1_2.geometry}
        material={gltf.materials.Green}
        position={[0.49, 0.72, -0.09]}
        rotation={[0.05, -0.03, 0.05]}
        scale={0.98}
      />
      <T.Mesh
        geometry={gltf.nodes.e_fracturepart1_3.geometry}
        material={gltf.materials.Green}
        position={[0.45, 0.34, -0.43]}
        rotation={[-0.05, -0.06, 0.04]}
        scale={0.97}
      />
      <T.Mesh
        geometry={gltf.nodes.e_fracturepart5_1.geometry}
        material={gltf.materials.Green}
        position={[0.51, 0.53, -0.55]}
        rotation={[-0.06, -0.07, -0.06]}
        scale={0.96}
      />
    </T.Group>
    <T.Group position={[0.27, 0.58, 0.37]} rotation={[0.01, -0.33, 0.16]}>
      <T.Mesh
        geometry={gltf.nodes.m_fracturepart1_6.geometry}
        material={gltf.materials.Green}
        position={[0.2, 0.26, -0.45]}
        rotation={[0.03, -0.06, 0.01]}
        scale={0.97}
      />
      <T.Mesh
        geometry={gltf.nodes.m_fracturepart1_7.geometry}
        material={gltf.materials.Green}
        position={[0.83, 0.06, -0.31]}
        rotation={[-0.07, 0, -0.03]}
      />
      <T.Mesh
        geometry={gltf.nodes.m_fracturepart1_8.geometry}
        material={gltf.materials.Green}
        position={[1.42, 0, -0.06]}
        rotation={[-0.03, 0.02, 0.04]}
        scale={1.01}
      />
      <T.Mesh
        geometry={gltf.nodes.m_fracturepart1_9.geometry}
        material={gltf.materials.Green}
        position={[1.43, -0.04, -0.15]}
        rotation={[-0.06, 0.08, -0.04]}
        scale={1.04}
      />
      <T.Mesh
        geometry={gltf.nodes.m_fracturepart1_10.geometry}
        material={gltf.materials.Green}
        position={[0.89, 0.07, -0.36]}
        rotation={[-0.05, 0.06, -0.07]}
        scale={1.03}
      />
      <T.Mesh
        geometry={gltf.nodes.m_fracturepart1_11.geometry}
        material={gltf.materials.Green}
        position={[0.21, 0.18, -0.55]}
        rotation={[-0.04, -0.05, -0.07]}
        scale={0.97}
      />
      <T.Mesh
        geometry={gltf.nodes.m_fracturepart5_1.geometry}
        material={gltf.materials.Green}
        position={[0.91, 0.54, -0.48]}
        rotation={[0.04, 0.04, 0]}
        scale={1.02}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.J_fracturepart_1.geometry}
      material={gltf.materials.Green}
      position={[-2.85, 2.31, -1.17]}
      rotation={[0.08, -0.34, 0.2]}
      scale={0.99}
    />
    <T.Mesh
      geometry={gltf.nodes.S_fracturepart_1.geometry}
      material={gltf.materials.Green}
      position={[-4.53, 0.39, -1.73]}
      rotation={[-0.02, -0.33, 0.21]}
    />
    <T.Mesh
      geometry={gltf.nodes.c_fracturepart_1.geometry}
      material={gltf.materials.Green}
      position={[-3.58, 0.42, -1.51]}
      rotation={[0.01, -0.38, 0.11]}
      scale={0.97}
    />
    <T.Mesh
      geometry={gltf.nodes.a_fracturepart_1.geometry}
      material={gltf.materials.Green}
      position={[2.37, 1.45, 0.61]}
      rotation={[0.08, -0.39, 0.2]}
      scale={0.96}
    />
    <T.Mesh
      geometry={gltf.nodes.n_fracturepart_1.geometry}
      material={gltf.materials.Green}
      position={[3.52, 1.54, 0.97]}
      rotation={[-0.05, -0.28, 0.12]}
      scale={1.04}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
