<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 /home/jschill/code/svelte/threlte_test/static/models/JSTitleScreen.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      ['CS_@_FSU']: THREE.Mesh
      Justin_Schilleman: THREE.Mesh
    }
    materials: {
      White: THREE.MeshStandardMaterial
      Green: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/JSTitleScreen.gltf')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes['CS_@_FSU'].geometry} material={gltf.materials.White} position={[-0.86, -0.6, 0]} />
    <T.Mesh
      geometry={gltf.nodes.Justin_Schilleman.geometry}
      material={gltf.materials.Green}
      position={[-0.43, 0.97, 0]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
