<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 /home/jschill/code/svelte/threlte_test/static/models/Stars.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Sphere1: THREE.Mesh
      Sphere2: THREE.Mesh
      Sphere3: THREE.Mesh
      Sphere4: THREE.Mesh
      Sphere5: THREE.Mesh
      Sphere6: THREE.Mesh
      Sphere7: THREE.Mesh
      Sphere8: THREE.Mesh
      Sphere9: THREE.Mesh
      Sphere10: THREE.Mesh
      Sphere11: THREE.Mesh
      Sphere12: THREE.Mesh
      Sphere13: THREE.Mesh
      Sphere14: THREE.Mesh
      Sphere15: THREE.Mesh
      Sphere16: THREE.Mesh
      Sphere17: THREE.Mesh
      Sphere18: THREE.Mesh
      Sphere19: THREE.Mesh
      Sphere20: THREE.Mesh
      Sphere21: THREE.Mesh
      Sphere22: THREE.Mesh
      Sphere23: THREE.Mesh
      Sphere24: THREE.Mesh
      Sphere25: THREE.Mesh
      Sphere26: THREE.Mesh
      Sphere27: THREE.Mesh
      Sphere28: THREE.Mesh
      Sphere29: THREE.Mesh
      Sphere30: THREE.Mesh
      Sphere31: THREE.Mesh
      Sphere32: THREE.Mesh
      Sphere33: THREE.Mesh
      Sphere34: THREE.Mesh
      Sphere35: THREE.Mesh
      Sphere36: THREE.Mesh
      Sphere37: THREE.Mesh
      Sphere38: THREE.Mesh
      Sphere39: THREE.Mesh
      Sphere40: THREE.Mesh
      Sphere41: THREE.Mesh
      Sphere42: THREE.Mesh
      Sphere43: THREE.Mesh
      Sphere44: THREE.Mesh
      Sphere45: THREE.Mesh
      Sphere46: THREE.Mesh
      Sphere47: THREE.Mesh
      Sphere48: THREE.Mesh
      Sphere49: THREE.Mesh
      Sphere50: THREE.Mesh
      Sphere51: THREE.Mesh
      Sphere52: THREE.Mesh
      Sphere53: THREE.Mesh
      Sphere54: THREE.Mesh
      Sphere55: THREE.Mesh
      Sphere56: THREE.Mesh
      Sphere57: THREE.Mesh
      Sphere58: THREE.Mesh
      Sphere59: THREE.Mesh
      Sphere60: THREE.Mesh
      Sphere61: THREE.Mesh
      Sphere62: THREE.Mesh
      Sphere63: THREE.Mesh
      Sphere64: THREE.Mesh
      Sphere65: THREE.Mesh
      Sphere66: THREE.Mesh
      Sphere67: THREE.Mesh
      Sphere68: THREE.Mesh
      Sphere69: THREE.Mesh
      Sphere70: THREE.Mesh
      Sphere71: THREE.Mesh
      Sphere72: THREE.Mesh
      Sphere73: THREE.Mesh
      Sphere74: THREE.Mesh
      Sphere75: THREE.Mesh
      Sphere76: THREE.Mesh
      Sphere77: THREE.Mesh
      Sphere78: THREE.Mesh
      Sphere79: THREE.Mesh
      Sphere80: THREE.Mesh
      Sphere81: THREE.Mesh
      Sphere82: THREE.Mesh
      Sphere83: THREE.Mesh
      Sphere84: THREE.Mesh
      Sphere85: THREE.Mesh
      Sphere86: THREE.Mesh
      Sphere87: THREE.Mesh
      Sphere88: THREE.Mesh
      Sphere89: THREE.Mesh
      Sphere90: THREE.Mesh
      Sphere91: THREE.Mesh
      Sphere92: THREE.Mesh
      Sphere93: THREE.Mesh
      Sphere94: THREE.Mesh
      Sphere95: THREE.Mesh
      Sphere96: THREE.Mesh
      Sphere97: THREE.Mesh
      Sphere98: THREE.Mesh
      Sphere99: THREE.Mesh
      Sphere100: THREE.Mesh
      Sphere101: THREE.Mesh
      Sphere102: THREE.Mesh
      Sphere103: THREE.Mesh
      Sphere104: THREE.Mesh
      Sphere105: THREE.Mesh
      Sphere106: THREE.Mesh
      Sphere107: THREE.Mesh
      Sphere108: THREE.Mesh
      Sphere109: THREE.Mesh
      Sphere110: THREE.Mesh
      Sphere111: THREE.Mesh
      Sphere112: THREE.Mesh
      Sphere113: THREE.Mesh
      Sphere114: THREE.Mesh
      Sphere115: THREE.Mesh
      Sphere116: THREE.Mesh
      Sphere117: THREE.Mesh
      Sphere118: THREE.Mesh
      Sphere119: THREE.Mesh
      Sphere120: THREE.Mesh
      Sphere121: THREE.Mesh
      Sphere122: THREE.Mesh
      Sphere123: THREE.Mesh
      Sphere124: THREE.Mesh
      Sphere125: THREE.Mesh
      Sphere126: THREE.Mesh
      Sphere127: THREE.Mesh
      Sphere128: THREE.Mesh
      Sphere129: THREE.Mesh
      Sphere130: THREE.Mesh
      Sphere131: THREE.Mesh
      Sphere132: THREE.Mesh
      Sphere133: THREE.Mesh
      Sphere134: THREE.Mesh
      Sphere135: THREE.Mesh
      Sphere136: THREE.Mesh
      Sphere137: THREE.Mesh
      Sphere138: THREE.Mesh
      Sphere139: THREE.Mesh
      Sphere140: THREE.Mesh
      Sphere141: THREE.Mesh
      Sphere142: THREE.Mesh
      Sphere143: THREE.Mesh
      Sphere144: THREE.Mesh
      Sphere145: THREE.Mesh
      Sphere146: THREE.Mesh
      Sphere147: THREE.Mesh
      Sphere148: THREE.Mesh
      Sphere149: THREE.Mesh
      Sphere150: THREE.Mesh
      Sphere151: THREE.Mesh
      Sphere152: THREE.Mesh
      Sphere153: THREE.Mesh
      Sphere154: THREE.Mesh
      Sphere155: THREE.Mesh
      Sphere156: THREE.Mesh
      Sphere157: THREE.Mesh
      Sphere158: THREE.Mesh
      Sphere159: THREE.Mesh
      Sphere160: THREE.Mesh
      Sphere161: THREE.Mesh
      Sphere162: THREE.Mesh
      Sphere163: THREE.Mesh
      Sphere164: THREE.Mesh
      Sphere165: THREE.Mesh
      Sphere166: THREE.Mesh
      Sphere167: THREE.Mesh
      Sphere168: THREE.Mesh
      Sphere169: THREE.Mesh
      Sphere170: THREE.Mesh
      Sphere171: THREE.Mesh
      Sphere172: THREE.Mesh
      Sphere173: THREE.Mesh
      Sphere174: THREE.Mesh
      Sphere175: THREE.Mesh
      Sphere176: THREE.Mesh
      Sphere177: THREE.Mesh
      Sphere178: THREE.Mesh
      Sphere179: THREE.Mesh
      Sphere180: THREE.Mesh
      Sphere181: THREE.Mesh
      Sphere182: THREE.Mesh
      Sphere183: THREE.Mesh
      Sphere184: THREE.Mesh
      Sphere185: THREE.Mesh
      Sphere186: THREE.Mesh
      Sphere187: THREE.Mesh
      Sphere188: THREE.Mesh
      Sphere189: THREE.Mesh
      Sphere190: THREE.Mesh
      Sphere191: THREE.Mesh
      Sphere192: THREE.Mesh
      Sphere193: THREE.Mesh
      Sphere194: THREE.Mesh
      Sphere195: THREE.Mesh
      Sphere196: THREE.Mesh
      Sphere197: THREE.Mesh
      Sphere198: THREE.Mesh
      Sphere199: THREE.Mesh
      Sphere200: THREE.Mesh
      Sphere201: THREE.Mesh
      Sphere202: THREE.Mesh
      Sphere203: THREE.Mesh
      Sphere204: THREE.Mesh
      Sphere205: THREE.Mesh
      Sphere206: THREE.Mesh
      Sphere207: THREE.Mesh
      Sphere208: THREE.Mesh
      Sphere209: THREE.Mesh
      Sphere210: THREE.Mesh
      Sphere211: THREE.Mesh
      Sphere212: THREE.Mesh
      Sphere213: THREE.Mesh
      Sphere214: THREE.Mesh
      Sphere215: THREE.Mesh
      Sphere216: THREE.Mesh
      Sphere217: THREE.Mesh
      Sphere218: THREE.Mesh
      Sphere219: THREE.Mesh
      Sphere220: THREE.Mesh
      Sphere221: THREE.Mesh
      Sphere222: THREE.Mesh
      Sphere223: THREE.Mesh
      Sphere224: THREE.Mesh
      Sphere225: THREE.Mesh
      Sphere226: THREE.Mesh
      Sphere227: THREE.Mesh
      Sphere228: THREE.Mesh
      Sphere229: THREE.Mesh
      Sphere230: THREE.Mesh
      Sphere231: THREE.Mesh
      Sphere232: THREE.Mesh
      Sphere233: THREE.Mesh
      Sphere234: THREE.Mesh
      Sphere235: THREE.Mesh
      Sphere236: THREE.Mesh
      Sphere237: THREE.Mesh
      Sphere238: THREE.Mesh
      Sphere239: THREE.Mesh
      Sphere240: THREE.Mesh
      Sphere241: THREE.Mesh
      Sphere242: THREE.Mesh
      Sphere243: THREE.Mesh
      Sphere244: THREE.Mesh
      Sphere245: THREE.Mesh
      Sphere246: THREE.Mesh
      Sphere1_1: THREE.Mesh
      Sphere2_1: THREE.Mesh
      Sphere3_1: THREE.Mesh
      Sphere4_1: THREE.Mesh
      Sphere5_1: THREE.Mesh
      Sphere6_1: THREE.Mesh
      Sphere7_1: THREE.Mesh
      Sphere8_1: THREE.Mesh
      Sphere9_1: THREE.Mesh
      Sphere10_1: THREE.Mesh
      Sphere11_1: THREE.Mesh
      Sphere12_1: THREE.Mesh
      Sphere13_1: THREE.Mesh
      Sphere14_1: THREE.Mesh
      Sphere15_1: THREE.Mesh
      Sphere16_1: THREE.Mesh
      Sphere17_1: THREE.Mesh
      Sphere18_1: THREE.Mesh
      Sphere19_1: THREE.Mesh
      Sphere20_1: THREE.Mesh
      Sphere21_1: THREE.Mesh
      Sphere22_1: THREE.Mesh
      Sphere23_1: THREE.Mesh
      Sphere24_1: THREE.Mesh
      Sphere25_1: THREE.Mesh
      Sphere26_1: THREE.Mesh
      Sphere27_1: THREE.Mesh
      Sphere28_1: THREE.Mesh
      Sphere29_1: THREE.Mesh
      Sphere30_1: THREE.Mesh
      Sphere31_1: THREE.Mesh
      Sphere32_1: THREE.Mesh
      Sphere33_1: THREE.Mesh
      Sphere34_1: THREE.Mesh
      Sphere35_1: THREE.Mesh
      Sphere36_1: THREE.Mesh
      Sphere37_1: THREE.Mesh
      Sphere38_1: THREE.Mesh
      Sphere39_1: THREE.Mesh
      Sphere40_1: THREE.Mesh
      Sphere41_1: THREE.Mesh
      Sphere42_1: THREE.Mesh
      Sphere43_1: THREE.Mesh
      Sphere44_1: THREE.Mesh
      Sphere45_1: THREE.Mesh
      Sphere46_1: THREE.Mesh
      Sphere47_1: THREE.Mesh
      Sphere48_1: THREE.Mesh
      Sphere49_1: THREE.Mesh
      Sphere50_1: THREE.Mesh
      Sphere51_1: THREE.Mesh
      Sphere52_1: THREE.Mesh
      Sphere53_1: THREE.Mesh
      Sphere54_1: THREE.Mesh
      Sphere55_1: THREE.Mesh
      Sphere56_1: THREE.Mesh
      Sphere57_1: THREE.Mesh
      Sphere58_1: THREE.Mesh
      Sphere59_1: THREE.Mesh
      Sphere60_1: THREE.Mesh
      Sphere61_1: THREE.Mesh
      Sphere1_2: THREE.Mesh
      Sphere2_2: THREE.Mesh
      Sphere3_2: THREE.Mesh
      Sphere4_2: THREE.Mesh
      Sphere5_2: THREE.Mesh
      Sphere6_2: THREE.Mesh
      Sphere7_2: THREE.Mesh
      Sphere8_2: THREE.Mesh
      Sphere9_2: THREE.Mesh
      Sphere10_2: THREE.Mesh
      Sphere11_2: THREE.Mesh
      Sphere12_2: THREE.Mesh
      Sphere13_2: THREE.Mesh
      Sphere14_2: THREE.Mesh
      Sphere15_2: THREE.Mesh
      Sphere16_2: THREE.Mesh
      Sphere17_2: THREE.Mesh
      Sphere18_2: THREE.Mesh
      Sphere19_2: THREE.Mesh
      Sphere20_2: THREE.Mesh
      Sphere21_2: THREE.Mesh
      Sphere22_2: THREE.Mesh
      Sphere23_2: THREE.Mesh
      Sphere24_2: THREE.Mesh
      Sphere25_2: THREE.Mesh
      Sphere26_2: THREE.Mesh
      Sphere27_2: THREE.Mesh
      Sphere28_2: THREE.Mesh
      Sphere29_2: THREE.Mesh
      Sphere30_2: THREE.Mesh
      Sphere31_2: THREE.Mesh
      Sphere32_2: THREE.Mesh
      Sphere33_2: THREE.Mesh
      Sphere34_2: THREE.Mesh
      Sphere35_2: THREE.Mesh
      Sphere36_2: THREE.Mesh
      Sphere37_2: THREE.Mesh
      Sphere38_2: THREE.Mesh
      Sphere39_2: THREE.Mesh
      Sphere40_2: THREE.Mesh
      Sphere41_2: THREE.Mesh
      Sphere42_2: THREE.Mesh
      Sphere43_2: THREE.Mesh
      Sphere44_2: THREE.Mesh
      Sphere45_2: THREE.Mesh
      Sphere46_2: THREE.Mesh
      Sphere47_2: THREE.Mesh
      Sphere48_2: THREE.Mesh
    }
    materials: {
      White: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Stars.gltf')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Sphere1.geometry}
      material={gltf.materials.White}
      position={[-0.29, 7.43, -11.32]}
      rotation={[0, 0.03, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere2.geometry}
      material={gltf.materials.White}
      position={[-0.58, 11.62, -11.31]}
      rotation={[0, 0.05, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere3.geometry}
      material={gltf.materials.White}
      position={[-0.87, -0.92, -11.29]}
      rotation={[0, 0.08, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere4.geometry}
      material={gltf.materials.White}
      position={[-1.15, 10.62, -11.26]}
      rotation={[0, 0.1, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere5.geometry}
      material={gltf.materials.White}
      position={[-1.44, 8.69, -11.23]}
      rotation={[0, 0.13, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere6.geometry}
      material={gltf.materials.White}
      position={[-1.73, -0.43, -11.19]}
      rotation={[0, 0.15, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere7.geometry}
      material={gltf.materials.White}
      position={[-2.01, 12.93, -11.14]}
      rotation={[0, 0.18, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere8.geometry}
      material={gltf.materials.White}
      position={[-2.3, 5.3, -11.08]}
      rotation={[0, 0.2, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere9.geometry}
      material={gltf.materials.White}
      position={[-2.58, 1.5, -11.02]}
      rotation={[0, 0.23, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere10.geometry}
      material={gltf.materials.White}
      position={[-2.86, 13.9, -10.95]}
      rotation={[0, 0.26, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere11.geometry}
      material={gltf.materials.White}
      position={[-3.14, 2.15, -10.88]}
      rotation={[0, 0.28, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere12.geometry}
      material={gltf.materials.White}
      position={[-3.42, 4.49, -10.79]}
      rotation={[0, 0.31, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere13.geometry}
      material={gltf.materials.White}
      position={[-3.69, 13.3, -10.7]}
      rotation={[0, 0.33, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere14.geometry}
      material={gltf.materials.White}
      position={[-3.96, -0.09, -10.6]}
      rotation={[0, 0.36, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere15.geometry}
      material={gltf.materials.White}
      position={[-4.23, 7.89, -10.5]}
      rotation={[0, 0.38, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere16.geometry}
      material={gltf.materials.White}
      position={[-4.5, 11.28, -10.39]}
      rotation={[0, 0.41, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere17.geometry}
      material={gltf.materials.White}
      position={[-4.76, -0.95, -10.27]}
      rotation={[0, 0.43, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere18.geometry}
      material={gltf.materials.White}
      position={[-5.02, 10.99, -10.14]}
      rotation={[0, 0.46, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere19.geometry}
      material={gltf.materials.White}
      position={[-5.28, 8.25, -10.01]}
      rotation={[0, 0.49, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere20.geometry}
      material={gltf.materials.White}
      position={[-5.53, -0.25, -9.87]}
      rotation={[0, 0.51, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere21.geometry}
      material={gltf.materials.White}
      position={[-5.78, 13.15, -9.73]}
      rotation={[0, 0.54, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere22.geometry}
      material={gltf.materials.White}
      position={[-6.03, 4.85, -9.58]}
      rotation={[0, 0.56, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere23.geometry}
      material={gltf.materials.White}
      position={[-6.27, 1.85, -9.42]}
      rotation={[0, 0.59, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere24.geometry}
      material={gltf.materials.White}
      position={[-6.51, 13.91, -9.26]}
      rotation={[0, 0.61, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere25.geometry}
      material={gltf.materials.White}
      position={[-6.75, 1.79, -9.09]}
      rotation={[0, 0.64, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere26.geometry}
      material={gltf.materials.White}
      position={[-6.98, 4.93, -8.91]}
      rotation={[0, 0.66, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere27.geometry}
      material={gltf.materials.White}
      position={[-7.2, 13.11, -8.73]}
      rotation={[0, 0.69, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere28.geometry}
      material={gltf.materials.White}
      position={[-7.42, -0.29, -8.55]}
      rotation={[0, 0.72, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere29.geometry}
      material={gltf.materials.White}
      position={[-7.64, 8.33, -8.35]}
      rotation={[0, 0.74, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere30.geometry}
      material={gltf.materials.White}
      position={[-7.85, 10.92, -8.16]}
      rotation={[0, 0.77, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere31.geometry}
      material={gltf.materials.White}
      position={[-8.06, -0.95, -7.95]}
      rotation={[0, 0.79, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere32.geometry}
      material={gltf.materials.White}
      position={[-8.26, 11.35, -7.74]}
      rotation={[0, 0.82, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere33.geometry}
      material={gltf.materials.White}
      position={[-8.45, 7.8, -7.53]}
      rotation={[0, 0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere34.geometry}
      material={gltf.materials.White}
      position={[-8.64, -0.05, -7.31]}
      rotation={[0, 0.87, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere35.geometry}
      material={gltf.materials.White}
      position={[-8.82, 13.34, -7.09]}
      rotation={[0, 0.89, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere36.geometry}
      material={gltf.materials.White}
      position={[-9, 4.4, -6.86]}
      rotation={[0, 0.92, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere37.geometry}
      material={gltf.materials.White}
      position={[-9.18, 2.22, -6.63]}
      rotation={[0, 0.95, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere38.geometry}
      material={gltf.materials.White}
      position={[-9.34, 13.89, -6.39]}
      rotation={[0, 0.97, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere39.geometry}
      material={gltf.materials.White}
      position={[-9.5, 1.44, -6.15]}
      rotation={[0, 1, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere40.geometry}
      material={gltf.materials.White}
      position={[-9.66, 5.38, -5.91]}
      rotation={[0, 1.02, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere41.geometry}
      material={gltf.materials.White}
      position={[-9.8, 12.89, -5.66]}
      rotation={[0, Math.PI / 3, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere42.geometry}
      material={gltf.materials.White}
      position={[-9.94, -0.47, -5.41]}
      rotation={[0, 1.07, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere43.geometry}
      material={gltf.materials.White}
      position={[-10.08, 8.77, -5.15]}
      rotation={[0, 1.1, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere44.geometry}
      material={gltf.materials.White}
      position={[-10.21, 10.54, -4.89]}
      rotation={[0, 1.12, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere45.geometry}
      material={gltf.materials.White}
      position={[-10.33, -0.92, -4.63]}
      rotation={[0, 1.15, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere46.geometry}
      material={gltf.materials.White}
      position={[-10.44, 11.68, -4.37]}
      rotation={[0, 1.17, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere47.geometry}
      material={gltf.materials.White}
      position={[-10.55, 7.35, -4.1]}
      rotation={[0, 1.2, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere48.geometry}
      material={gltf.materials.White}
      position={[-10.65, 0.19, -3.83]}
      rotation={[0, 1.23, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere49.geometry}
      material={gltf.materials.White}
      position={[-10.75, 13.5, -3.55]}
      rotation={[0, 1.25, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere50.geometry}
      material={gltf.materials.White}
      position={[-10.84, 3.97, -3.28]}
      rotation={[0, 1.28, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere51.geometry}
      material={gltf.materials.White}
      position={[-10.92, 2.61, -3]}
      rotation={[0, 1.3, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere52.geometry}
      material={gltf.materials.White}
      position={[-10.99, 13.85, -2.72]}
      rotation={[0, 1.33, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere53.geometry}
      material={gltf.materials.White}
      position={[-11.05, 1.11, -2.44]}
      rotation={[0, 1.35, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere54.geometry}
      material={gltf.materials.White}
      position={[-11.11, 5.84, -2.16]}
      rotation={[0, 1.38, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere55.geometry}
      material={gltf.materials.White}
      position={[-11.16, 12.65, -1.87]}
      rotation={[0, 1.4, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere56.geometry}
      material={gltf.materials.White}
      position={[-11.21, -0.62, -1.58]}
      rotation={[0, 1.43, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere57.geometry}
      material={gltf.materials.White}
      position={[-11.25, 9.21, -1.3]}
      rotation={[0, 1.46, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere58.geometry}
      material={gltf.materials.White}
      position={[-11.27, 10.15, -1.01]}
      rotation={[0, 1.48, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere59.geometry}
      material={gltf.materials.White}
      position={[-11.3, -0.86, -0.72]}
      rotation={[0, 1.51, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere60.geometry}
      material={gltf.materials.White}
      position={[-11.31, 12, -0.43]}
      rotation={[0, 1.53, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere61.geometry}
      material={gltf.materials.White}
      position={[-11.32, 6.89, -0.14]}
      rotation={[0, 1.56, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere62.geometry}
      material={gltf.materials.White}
      position={[-11.32, 0.44, 0.14]}
      rotation={[-Math.PI, 1.56, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere63.geometry}
      material={gltf.materials.White}
      position={[-11.31, 13.64, 0.43]}
      rotation={[-Math.PI, 1.53, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere64.geometry}
      material={gltf.materials.White}
      position={[-11.3, 3.54, 0.72]}
      rotation={[-Math.PI, 1.51, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere65.geometry}
      material={gltf.materials.White}
      position={[-11.27, 3.01, 1.01]}
      rotation={[-Math.PI, 1.48, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere66.geometry}
      material={gltf.materials.White}
      position={[-11.25, 13.77, 1.3]}
      rotation={[-Math.PI, 1.46, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere67.geometry}
      material={gltf.materials.White}
      position={[-11.21, 0.8, 1.58]}
      rotation={[-Math.PI, 1.43, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere68.geometry}
      material={gltf.materials.White}
      position={[-11.16, 6.3, 1.87]}
      rotation={[-Math.PI, 1.4, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere69.geometry}
      material={gltf.materials.White}
      position={[-11.11, 12.38, 2.16]}
      rotation={[-Math.PI, 1.38, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere70.geometry}
      material={gltf.materials.White}
      position={[-11.05, -0.74, 2.44]}
      rotation={[-Math.PI, 1.35, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere71.geometry}
      material={gltf.materials.White}
      position={[-10.99, 9.63, 2.72]}
      rotation={[Math.PI, 1.33, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere72.geometry}
      material={gltf.materials.White}
      position={[-10.92, 9.75, 3]}
      rotation={[-Math.PI, 1.3, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere73.geometry}
      material={gltf.materials.White}
      position={[-10.84, -0.77, 3.28]}
      rotation={[-Math.PI, 1.28, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere74.geometry}
      material={gltf.materials.White}
      position={[-10.75, 12.3, 3.55]}
      rotation={[-Math.PI, 1.25, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere75.geometry}
      material={gltf.materials.White}
      position={[-10.65, 6.43, 3.83]}
      rotation={[-Math.PI, 1.23, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere76.geometry}
      material={gltf.materials.White}
      position={[-10.55, 0.72, 4.1]}
      rotation={[-Math.PI, 1.2, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere77.geometry}
      material={gltf.materials.White}
      position={[-10.44, 13.75, 4.37]}
      rotation={[-Math.PI, 1.17, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere78.geometry}
      material={gltf.materials.White}
      position={[-10.33, 3.12, 4.63]}
      rotation={[-Math.PI, 1.15, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere79.geometry}
      material={gltf.materials.White}
      position={[-10.21, 3.42, 4.89]}
      rotation={[-Math.PI, 1.12, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere80.geometry}
      material={gltf.materials.White}
      position={[-10.08, 13.67, 5.15]}
      rotation={[-Math.PI, 1.1, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere81.geometry}
      material={gltf.materials.White}
      position={[-9.94, 0.52, 5.41]}
      rotation={[-Math.PI, 1.07, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere82.geometry}
      material={gltf.materials.White}
      position={[-9.8, 6.76, 5.66]}
      rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere83.geometry}
      material={gltf.materials.White}
      position={[-9.66, 12.09, 5.91]}
      rotation={[-Math.PI, 1.02, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere84.geometry}
      material={gltf.materials.White}
      position={[-9.5, -0.83, 6.15]}
      rotation={[-Math.PI, 1, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere85.geometry}
      material={gltf.materials.White}
      position={[-9.34, 10.04, 6.39]}
      rotation={[-Math.PI, 0.97, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere86.geometry}
      material={gltf.materials.White}
      position={[-9.18, 9.33, 6.63]}
      rotation={[-Math.PI, 0.95, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere87.geometry}
      material={gltf.materials.White}
      position={[-9, -0.65, 6.86]}
      rotation={[-Math.PI, 0.92, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere88.geometry}
      material={gltf.materials.White}
      position={[-8.82, 12.57, 7.09]}
      rotation={[-Math.PI, 0.89, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere89.geometry}
      material={gltf.materials.White}
      position={[-8.64, 5.97, 7.31]}
      rotation={[-Math.PI, 0.87, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere90.geometry}
      material={gltf.materials.White}
      position={[-8.45, 1.02, 7.53]}
      rotation={[-Math.PI, 0.84, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere91.geometry}
      material={gltf.materials.White}
      position={[-8.26, 13.83, 7.74]}
      rotation={[-Math.PI, 0.82, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere92.geometry}
      material={gltf.materials.White}
      position={[-8.06, 2.72, 7.95]}
      rotation={[-Math.PI, 0.79, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere93.geometry}
      material={gltf.materials.White}
      position={[-7.85, 3.84, 8.16]}
      rotation={[-Math.PI, 0.77, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere94.geometry}
      material={gltf.materials.White}
      position={[-7.64, 13.54, 8.35]}
      rotation={[-Math.PI, 0.74, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere95.geometry}
      material={gltf.materials.White}
      position={[-7.42, 0.26, 8.55]}
      rotation={[-Math.PI, 0.72, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere96.geometry}
      material={gltf.materials.White}
      position={[-7.2, 7.22, 8.73]}
      rotation={[-Math.PI, 0.69, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere97.geometry}
      material={gltf.materials.White}
      position={[-6.98, 11.78, 8.91]}
      rotation={[-Math.PI, 0.66, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere98.geometry}
      material={gltf.materials.White}
      position={[-6.75, -0.9, 9.09]}
      rotation={[-Math.PI, 0.64, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere99.geometry}
      material={gltf.materials.White}
      position={[-6.51, 10.43, 9.26]}
      rotation={[-Math.PI, 0.61, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere100.geometry}
      material={gltf.materials.White}
      position={[-6.27, 8.9, 9.42]}
      rotation={[-Math.PI, 0.59, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere101.geometry}
      material={gltf.materials.White}
      position={[-6.03, -0.51, 9.58]}
      rotation={[-Math.PI, 0.56, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere102.geometry}
      material={gltf.materials.White}
      position={[-5.78, 12.82, 9.73]}
      rotation={[-Math.PI, 0.54, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere103.geometry}
      material={gltf.materials.White}
      position={[-5.53, 5.51, 9.87]}
      rotation={[-Math.PI, 0.51, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere104.geometry}
      material={gltf.materials.White}
      position={[-5.28, 1.34, 10.01]}
      rotation={[-Math.PI, 0.49, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere105.geometry}
      material={gltf.materials.White}
      position={[-5.02, 13.88, 10.14]}
      rotation={[-Math.PI, 0.46, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere106.geometry}
      material={gltf.materials.White}
      position={[-4.76, 2.33, 10.27]}
      rotation={[-Math.PI, 0.43, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere107.geometry}
      material={gltf.materials.White}
      position={[-4.5, 4.28, 10.39]}
      rotation={[-Math.PI, 0.41, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere108.geometry}
      material={gltf.materials.White}
      position={[-4.23, 13.39, 10.5]}
      rotation={[-Math.PI, 0.38, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere109.geometry}
      material={gltf.materials.White}
      position={[-3.96, 0.02, 10.6]}
      rotation={[-Math.PI, 0.36, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere110.geometry}
      material={gltf.materials.White}
      position={[-3.69, 7.67, 10.7]}
      rotation={[-Math.PI, 0.33, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere111.geometry}
      material={gltf.materials.White}
      position={[-3.42, 11.44, 10.79]}
      rotation={[-Math.PI, 0.31, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere112.geometry}
      material={gltf.materials.White}
      position={[-3.14, -0.94, 10.88]}
      rotation={[-Math.PI, 0.28, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere113.geometry}
      material={gltf.materials.White}
      position={[-2.86, 10.82, 10.95]}
      rotation={[-Math.PI, 0.26, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere114.geometry}
      material={gltf.materials.White}
      position={[-2.58, 8.46, 11.02]}
      rotation={[-Math.PI, 0.23, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere115.geometry}
      material={gltf.materials.White}
      position={[-2.3, -0.34, 11.08]}
      rotation={[-Math.PI, 0.2, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere116.geometry}
      material={gltf.materials.White}
      position={[-2.01, 13.05, 11.14]}
      rotation={[-Math.PI, 0.18, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere117.geometry}
      material={gltf.materials.White}
      position={[-1.73, 5.06, 11.19]}
      rotation={[-Math.PI, 0.15, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere118.geometry}
      material={gltf.materials.White}
      position={[-1.44, 1.69, 11.23]}
      rotation={[-Math.PI, 0.13, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere119.geometry}
      material={gltf.materials.White}
      position={[-1.15, 13.91, 11.26]}
      rotation={[-Math.PI, 0.1, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere120.geometry}
      material={gltf.materials.White}
      position={[-0.87, 1.96, 11.29]}
      rotation={[-Math.PI, 0.08, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere121.geometry}
      material={gltf.materials.White}
      position={[-0.58, 4.72, 11.31]}
      rotation={[-Math.PI, 0.05, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere122.geometry}
      material={gltf.materials.White}
      position={[-0.29, 13.21, 11.32]}
      rotation={[-Math.PI, 0.03, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere123.geometry}
      material={gltf.materials.White}
      position={[0, -0.2, 11.32]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere124.geometry}
      material={gltf.materials.White}
      position={[0.29, 8.12, 11.32]}
      rotation={[Math.PI, -0.03, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere125.geometry}
      material={gltf.materials.White}
      position={[0.58, 11.09, 11.31]}
      rotation={[Math.PI, -0.05, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere126.geometry}
      material={gltf.materials.White}
      position={[0.87, -0.95, 11.29]}
      rotation={[Math.PI, -0.08, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere127.geometry}
      material={gltf.materials.White}
      position={[1.15, 11.18, 11.26]}
      rotation={[-Math.PI, -0.1, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere128.geometry}
      material={gltf.materials.White}
      position={[1.44, 8.01, 11.23]}
      rotation={[Math.PI, -0.13, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere129.geometry}
      material={gltf.materials.White}
      position={[1.73, -0.15, 11.19]}
      rotation={[Math.PI, -0.15, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere130.geometry}
      material={gltf.materials.White}
      position={[2.01, 13.25, 11.14]}
      rotation={[Math.PI, -0.18, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere131.geometry}
      material={gltf.materials.White}
      position={[2.3, 4.61, 11.08]}
      rotation={[-Math.PI, -0.2, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere132.geometry}
      material={gltf.materials.White}
      position={[2.58, 2.05, 11.02]}
      rotation={[Math.PI, -0.23, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere133.geometry}
      material={gltf.materials.White}
      position={[2.86, 13.9, 10.95]}
      rotation={[Math.PI, -0.26, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere134.geometry}
      material={gltf.materials.White}
      position={[3.14, 1.6, 10.88]}
      rotation={[Math.PI, -0.28, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere135.geometry}
      material={gltf.materials.White}
      position={[3.42, 5.17, 10.79]}
      rotation={[Math.PI, -0.31, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere136.geometry}
      material={gltf.materials.White}
      position={[3.69, 13, 10.7]}
      rotation={[Math.PI, -0.33, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere137.geometry}
      material={gltf.materials.White}
      position={[3.96, -0.39, 10.6]}
      rotation={[Math.PI, -0.36, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere138.geometry}
      material={gltf.materials.White}
      position={[4.23, 8.57, 10.5]}
      rotation={[-Math.PI, -0.38, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere139.geometry}
      material={gltf.materials.White}
      position={[4.5, 10.72, 10.39]}
      rotation={[Math.PI, -0.41, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere140.geometry}
      material={gltf.materials.White}
      position={[4.76, -0.93, 10.27]}
      rotation={[Math.PI, -0.43, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere141.geometry}
      material={gltf.materials.White}
      position={[5.02, 11.53, 10.14]}
      rotation={[Math.PI, -0.46, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere142.geometry}
      material={gltf.materials.White}
      position={[5.28, 7.56, 10.01]}
      rotation={[Math.PI, -0.49, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere143.geometry}
      material={gltf.materials.White}
      position={[5.53, 0.07, 9.87]}
      rotation={[Math.PI, -0.51, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere144.geometry}
      material={gltf.materials.White}
      position={[5.78, 13.43, 9.73]}
      rotation={[Math.PI, -0.54, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere145.geometry}
      material={gltf.materials.White}
      position={[6.03, 4.17, 9.58]}
      rotation={[Math.PI, -0.56, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere146.geometry}
      material={gltf.materials.White}
      position={[6.27, 2.42, 9.42]}
      rotation={[Math.PI, -0.59, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere147.geometry}
      material={gltf.materials.White}
      position={[6.51, 13.87, 9.26]}
      rotation={[Math.PI, -0.61, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere148.geometry}
      material={gltf.materials.White}
      position={[6.75, 1.26, 9.09]}
      rotation={[Math.PI, -0.64, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere149.geometry}
      material={gltf.materials.White}
      position={[6.98, 5.62, 8.91]}
      rotation={[-Math.PI, -0.66, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere150.geometry}
      material={gltf.materials.White}
      position={[7.2, 12.76, 8.73]}
      rotation={[Math.PI, -0.69, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere151.geometry}
      material={gltf.materials.White}
      position={[7.42, -0.55, 8.55]}
      rotation={[Math.PI, -0.72, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere152.geometry}
      material={gltf.materials.White}
      position={[7.64, 9, 8.35]}
      rotation={[Math.PI, -0.74, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere153.geometry}
      material={gltf.materials.White}
      position={[7.85, 10.34, 8.16]}
      rotation={[Math.PI, -0.77, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere154.geometry}
      material={gltf.materials.White}
      position={[8.06, -0.89, 7.95]}
      rotation={[Math.PI, -0.79, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere155.geometry}
      material={gltf.materials.White}
      position={[8.26, 11.85, 7.74]}
      rotation={[Math.PI, -0.82, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere156.geometry}
      material={gltf.materials.White}
      position={[8.45, 7.11, 7.53]}
      rotation={[Math.PI, -0.84, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere157.geometry}
      material={gltf.materials.White}
      position={[8.64, 0.32, 7.31]}
      rotation={[Math.PI, -0.87, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere158.geometry}
      material={gltf.materials.White}
      position={[8.82, 13.58, 7.09]}
      rotation={[Math.PI, -0.89, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere159.geometry}
      material={gltf.materials.White}
      position={[9, 3.74, 6.86]}
      rotation={[Math.PI, -0.92, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere160.geometry}
      material={gltf.materials.White}
      position={[9.18, 2.82, 6.63]}
      rotation={[Math.PI, -0.95, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere161.geometry}
      material={gltf.materials.White}
      position={[9.34, 13.81, 6.39]}
      rotation={[Math.PI, -0.97, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere162.geometry}
      material={gltf.materials.White}
      position={[9.5, 0.95, 6.15]}
      rotation={[Math.PI, -1, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere163.geometry}
      material={gltf.materials.White}
      position={[9.66, 6.08, 5.91]}
      rotation={[Math.PI, -1.02, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere164.geometry}
      material={gltf.materials.White}
      position={[9.8, 12.51, 5.66]}
      rotation={[Math.PI, -Math.PI / 3, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere165.geometry}
      material={gltf.materials.White}
      position={[9.94, -0.68, 5.41]}
      rotation={[Math.PI, -1.07, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere166.geometry}
      material={gltf.materials.White}
      position={[10.08, 9.43, 5.15]}
      rotation={[Math.PI, -1.1, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere167.geometry}
      material={gltf.materials.White}
      position={[10.21, 9.94, 4.89]}
      rotation={[Math.PI, -1.12, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere168.geometry}
      material={gltf.materials.White}
      position={[10.33, -0.81, 4.63]}
      rotation={[Math.PI, -1.15, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere169.geometry}
      material={gltf.materials.White}
      position={[10.44, 12.16, 4.37]}
      rotation={[Math.PI, -1.17, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere170.geometry}
      material={gltf.materials.White}
      position={[10.55, 6.65, 4.1]}
      rotation={[Math.PI, -1.2, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere171.geometry}
      material={gltf.materials.White}
      position={[10.65, 0.59, 3.83]}
      rotation={[Math.PI, -1.23, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere172.geometry}
      material={gltf.materials.White}
      position={[10.75, 13.7, 3.55]}
      rotation={[Math.PI, -1.25, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere173.geometry}
      material={gltf.materials.White}
      position={[10.84, 3.32, 3.28]}
      rotation={[-Math.PI, -1.28, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere174.geometry}
      material={gltf.materials.White}
      position={[10.92, 3.22, 3]}
      rotation={[Math.PI, -1.3, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere175.geometry}
      material={gltf.materials.White}
      position={[10.99, 13.72, 2.72]}
      rotation={[-Math.PI, -1.33, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere176.geometry}
      material={gltf.materials.White}
      position={[11.05, 0.65, 2.44]}
      rotation={[Math.PI, -1.35, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere177.geometry}
      material={gltf.materials.White}
      position={[11.11, 6.54, 2.16]}
      rotation={[Math.PI, -1.38, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere178.geometry}
      material={gltf.materials.White}
      position={[11.16, 12.23, 1.87]}
      rotation={[Math.PI, -1.4, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere179.geometry}
      material={gltf.materials.White}
      position={[11.21, -0.79, 1.58]}
      rotation={[-Math.PI, -1.43, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere180.geometry}
      material={gltf.materials.White}
      position={[11.25, 9.85, 1.3]}
      rotation={[Math.PI, -1.46, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere181.geometry}
      material={gltf.materials.White}
      position={[11.27, 9.53, 1.01]}
      rotation={[Math.PI, -1.48, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere182.geometry}
      material={gltf.materials.White}
      position={[11.3, -0.71, 0.72]}
      rotation={[Math.PI, -1.51, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere183.geometry}
      material={gltf.materials.White}
      position={[11.31, 12.44, 0.43]}
      rotation={[Math.PI, -1.53, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere184.geometry}
      material={gltf.materials.White}
      position={[11.32, 6.19, 0.14]}
      rotation={[Math.PI, -1.56, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere185.geometry}
      material={gltf.materials.White}
      position={[11.32, 0.88, -0.14]}
      rotation={[0, -1.56, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere186.geometry}
      material={gltf.materials.White}
      position={[11.31, 13.79, -0.43]}
      rotation={[0, -1.53, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere187.geometry}
      material={gltf.materials.White}
      position={[11.3, 2.91, -0.72]}
      rotation={[0, -1.51, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere188.geometry}
      material={gltf.materials.White}
      position={[11.27, 3.64, -1.01]}
      rotation={[0, -1.48, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere189.geometry}
      material={gltf.materials.White}
      position={[11.25, 13.61, -1.3]}
      rotation={[0, -1.46, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere190.geometry}
      material={gltf.materials.White}
      position={[11.21, 0.38, -1.58]}
      rotation={[0, -1.43, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere191.geometry}
      material={gltf.materials.White}
      position={[11.16, 7, -1.87]}
      rotation={[0, -1.4, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere192.geometry}
      material={gltf.materials.White}
      position={[11.11, 11.93, -2.16]}
      rotation={[0, -1.38, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere193.geometry}
      material={gltf.materials.White}
      position={[11.05, -0.87, -2.44]}
      rotation={[0, -1.35, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere194.geometry}
      material={gltf.materials.White}
      position={[10.99, 10.25, -2.72]}
      rotation={[0, -1.33, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere195.geometry}
      material={gltf.materials.White}
      position={[10.92, 9.1, -3]}
      rotation={[0, -1.3, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere196.geometry}
      material={gltf.materials.White}
      position={[10.84, -0.58, -3.28]}
      rotation={[0, -1.28, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere197.geometry}
      material={gltf.materials.White}
      position={[10.75, 12.71, -3.55]}
      rotation={[0, -1.25, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere198.geometry}
      material={gltf.materials.White}
      position={[10.65, 5.73, -3.83]}
      rotation={[0, -1.23, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere199.geometry}
      material={gltf.materials.White}
      position={[10.55, 1.19, -4.1]}
      rotation={[0, -1.2, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere200.geometry}
      material={gltf.materials.White}
      position={[10.44, 13.86, -4.37]}
      rotation={[0, -1.17, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere201.geometry}
      material={gltf.materials.White}
      position={[10.33, 2.51, -4.63]}
      rotation={[0, -1.15, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere202.geometry}
      material={gltf.materials.White}
      position={[10.21, 4.07, -4.89]}
      rotation={[0, -1.12, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere203.geometry}
      material={gltf.materials.White}
      position={[10.08, 13.46, -5.15]}
      rotation={[0, -1.1, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere204.geometry}
      material={gltf.materials.White}
      position={[9.94, 0.13, -5.41]}
      rotation={[0, -1.07, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere205.geometry}
      material={gltf.materials.White}
      position={[9.8, 7.46, -5.66]}
      rotation={[0, -Math.PI / 3, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere206.geometry}
      material={gltf.materials.White}
      position={[9.66, 11.6, -5.91]}
      rotation={[0, -1.02, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere207.geometry}
      material={gltf.materials.White}
      position={[9.5, -0.93, -6.15]}
      rotation={[0, -1, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere208.geometry}
      material={gltf.materials.White}
      position={[9.34, 10.64, -6.39]}
      rotation={[0, -0.97, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere209.geometry}
      material={gltf.materials.White}
      position={[9.18, 8.67, -6.63]}
      rotation={[0, -0.95, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere210.geometry}
      material={gltf.materials.White}
      position={[9, -0.43, -6.86]}
      rotation={[0, -0.92, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere211.geometry}
      material={gltf.materials.White}
      position={[8.82, 12.95, -7.09]}
      rotation={[0, -0.89, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere212.geometry}
      material={gltf.materials.White}
      position={[8.64, 5.27, -7.31]}
      rotation={[0, -0.87, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere213.geometry}
      material={gltf.materials.White}
      position={[8.45, 1.52, -7.53]}
      rotation={[0, -0.84, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere214.geometry}
      material={gltf.materials.White}
      position={[8.26, 13.9, -7.74]}
      rotation={[0, -0.82, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere215.geometry}
      material={gltf.materials.White}
      position={[8.06, 2.13, -7.95]}
      rotation={[0, -0.79, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere216.geometry}
      material={gltf.materials.White}
      position={[7.85, 4.51, -8.16]}
      rotation={[0, -0.77, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere217.geometry}
      material={gltf.materials.White}
      position={[7.64, 13.3, -8.35]}
      rotation={[0, -0.74, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere218.geometry}
      material={gltf.materials.White}
      position={[7.42, -0.1, -8.55]}
      rotation={[0, -0.72, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere219.geometry}
      material={gltf.materials.White}
      position={[7.2, 7.91, -8.73]}
      rotation={[0, -0.69, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere220.geometry}
      material={gltf.materials.White}
      position={[6.98, 11.26, -8.91]}
      rotation={[0, -0.66, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere221.geometry}
      material={gltf.materials.White}
      position={[6.75, -0.95, -9.09]}
      rotation={[0, -0.64, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere222.geometry}
      material={gltf.materials.White}
      position={[6.51, 11.01, -9.26]}
      rotation={[0, -0.61, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere223.geometry}
      material={gltf.materials.White}
      position={[6.27, 8.23, -9.42]}
      rotation={[0, -0.59, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere224.geometry}
      material={gltf.materials.White}
      position={[6.03, -0.24, -9.58]}
      rotation={[0, -0.56, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere225.geometry}
      material={gltf.materials.White}
      position={[5.78, 13.16, -9.73]}
      rotation={[0, -0.54, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere226.geometry}
      material={gltf.materials.White}
      position={[5.53, 4.82, -9.87]}
      rotation={[0, -0.51, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere227.geometry}
      material={gltf.materials.White}
      position={[5.28, 1.87, -10.01]}
      rotation={[0, -0.49, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere228.geometry}
      material={gltf.materials.White}
      position={[5.02, 13.91, -10.14]}
      rotation={[0, -0.46, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere229.geometry}
      material={gltf.materials.White}
      position={[4.76, 1.77, -10.27]}
      rotation={[0, -0.43, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere230.geometry}
      material={gltf.materials.White}
      position={[4.5, 4.95, -10.39]}
      rotation={[0, -0.41, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere231.geometry}
      material={gltf.materials.White}
      position={[4.23, 13.1, -10.5]}
      rotation={[0, -0.38, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere232.geometry}
      material={gltf.materials.White}
      position={[3.96, -0.3, -10.6]}
      rotation={[0, -0.36, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere233.geometry}
      material={gltf.materials.White}
      position={[3.69, 8.36, -10.7]}
      rotation={[0, -0.33, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere234.geometry}
      material={gltf.materials.White}
      position={[3.42, 10.9, -10.79]}
      rotation={[0, -0.31, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere235.geometry}
      material={gltf.materials.White}
      position={[3.14, -0.95, -10.88]}
      rotation={[0, -0.28, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere236.geometry}
      material={gltf.materials.White}
      position={[2.86, 11.36, -10.95]}
      rotation={[0, -0.26, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere237.geometry}
      material={gltf.materials.White}
      position={[2.58, 7.78, -11.02]}
      rotation={[0, -0.23, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere238.geometry}
      material={gltf.materials.White}
      position={[2.3, -0.03, -11.08]}
      rotation={[0, -0.2, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere239.geometry}
      material={gltf.materials.White}
      position={[2.01, 13.35, -11.14]}
      rotation={[0, -0.18, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere240.geometry}
      material={gltf.materials.White}
      position={[1.73, 4.38, -11.19]}
      rotation={[0, -0.15, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere241.geometry}
      material={gltf.materials.White}
      position={[1.44, 2.24, -11.23]}
      rotation={[0, -0.13, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere242.geometry}
      material={gltf.materials.White}
      position={[1.15, 13.89, -11.26]}
      rotation={[0, -0.1, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere243.geometry}
      material={gltf.materials.White}
      position={[0.87, 1.42, -11.29]}
      rotation={[0, -0.08, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere244.geometry}
      material={gltf.materials.White}
      position={[0.58, 5.41, -11.31]}
      rotation={[0, -0.05, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere245.geometry}
      material={gltf.materials.White}
      position={[0.29, 12.88, -11.32]}
      rotation={[0, -0.03, 0]}
    />
    <T.Mesh geometry={gltf.nodes.Sphere246.geometry} material={gltf.materials.White} position={[0, -0.47, -11.32]} />
    <T.Mesh
      geometry={gltf.nodes.Sphere1_1.geometry}
      material={gltf.materials.White}
      position={[-0.77, 8.36, -7.44]}
      rotation={[0, 0.1, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere2_1.geometry}
      material={gltf.materials.White}
      position={[-1.53, 2.77, -7.32]}
      rotation={[0, 0.21, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere3_1.geometry}
      material={gltf.materials.White}
      position={[-2.27, -0.69, -7.13]}
      rotation={[0, 0.31, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere4_1.geometry}
      material={gltf.materials.White}
      position={[-3, 0, -6.85]}
      rotation={[0, 0.41, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere5_1.geometry}
      material={gltf.materials.White}
      position={[-3.68, 4.43, -6.51]}
      rotation={[0, 0.52, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere6_1.geometry}
      material={gltf.materials.White}
      position={[-4.33, 10.04, -6.1]}
      rotation={[0, 0.62, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere7_1.geometry}
      material={gltf.materials.White}
      position={[-4.94, 13.6, -5.62]}
      rotation={[0, 0.72, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere8_1.geometry}
      material={gltf.materials.White}
      position={[-5.49, 13.04, -5.08]}
      rotation={[0, 0.82, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere9_1.geometry}
      material={gltf.materials.White}
      position={[-5.98, 8.69, -4.49]}
      rotation={[0, 0.93, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere10_1.geometry}
      material={gltf.materials.White}
      position={[-6.41, 3.06, -3.85]}
      rotation={[0, 1.03, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere11_1.geometry}
      material={gltf.materials.White}
      position={[-6.77, -0.59, -3.17]}
      rotation={[0, 1.13, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere12_1.geometry}
      material={gltf.materials.White}
      position={[-7.06, -0.16, -2.46]}
      rotation={[0, 1.24, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere13_1.geometry}
      material={gltf.materials.White}
      position={[-7.28, 4.11, -1.72]}
      rotation={[0, 1.34, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere14_1.geometry}
      material={gltf.materials.White}
      position={[-7.42, 9.75, -0.96]}
      rotation={[0, 1.44, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere15_1.geometry}
      material={gltf.materials.White}
      position={[-7.48, 13.49, -0.19]}
      rotation={[0, 1.55, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere16_1.geometry}
      material={gltf.materials.White}
      position={[-7.46, 13.19, 0.58]}
      rotation={[-Math.PI, 1.49, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere17_1.geometry}
      material={gltf.materials.White}
      position={[-7.36, 9.01, 1.34]}
      rotation={[-Math.PI, 1.39, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere18_1.geometry}
      material={gltf.materials.White}
      position={[-7.18, 3.36, 2.09]}
      rotation={[-Math.PI, 1.29, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere19_1.geometry}
      material={gltf.materials.White}
      position={[-6.93, -0.48, 2.82]}
      rotation={[-Math.PI, 1.18, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere20_1.geometry}
      material={gltf.materials.White}
      position={[-6.6, -0.3, 3.52]}
      rotation={[-Math.PI, 1.08, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere21_1.geometry}
      material={gltf.materials.White}
      position={[-6.21, 3.79, 4.18]}
      rotation={[-Math.PI, 0.98, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere22_1.geometry}
      material={gltf.materials.White}
      position={[-5.74, 9.44, 4.79]}
      rotation={[-Math.PI, 0.88, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere23_1.geometry}
      material={gltf.materials.White}
      position={[-5.22, 13.38, 5.36]}
      rotation={[-Math.PI, 0.77, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere24_1.geometry}
      material={gltf.materials.White}
      position={[-4.64, 13.33, 5.87]}
      rotation={[-Math.PI, 0.67, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere25_1.geometry}
      material={gltf.materials.White}
      position={[-4.01, 9.32, 6.31]}
      rotation={[-Math.PI, 0.57, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere26_1.geometry}
      material={gltf.materials.White}
      position={[-3.34, 3.67, 6.69]}
      rotation={[-Math.PI, 0.46, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere27_1.geometry}
      material={gltf.materials.White}
      position={[-2.64, -0.35, 7]}
      rotation={[-Math.PI, 0.36, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere28_1.geometry}
      material={gltf.materials.White}
      position={[-1.9, -0.43, 7.23]}
      rotation={[-Math.PI, 0.26, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere29_1.geometry}
      material={gltf.materials.White}
      position={[-1.15, 3.48, 7.39]}
      rotation={[-Math.PI, 0.15, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere30_1.geometry}
      material={gltf.materials.White}
      position={[-0.39, 9.13, 7.47]}
      rotation={[-Math.PI, 0.05, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere31_1.geometry}
      material={gltf.materials.White}
      position={[0.39, 13.24, 7.47]}
      rotation={[Math.PI, -0.05, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere32_1.geometry}
      material={gltf.materials.White}
      position={[1.15, 13.45, 7.39]}
      rotation={[Math.PI, -0.15, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere33_1.geometry}
      material={gltf.materials.White}
      position={[1.9, 9.63, 7.23]}
      rotation={[Math.PI, -0.26, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere34_1.geometry}
      material={gltf.materials.White}
      position={[2.64, 3.99, 7]}
      rotation={[-Math.PI, -0.36, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere35_1.geometry}
      material={gltf.materials.White}
      position={[3.34, -0.21, 6.69]}
      rotation={[Math.PI, -0.46, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere36_1.geometry}
      material={gltf.materials.White}
      position={[4.01, -0.55, 6.31]}
      rotation={[Math.PI, -0.57, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere37_1.geometry}
      material={gltf.materials.White}
      position={[4.64, 3.18, 5.87]}
      rotation={[Math.PI, -0.67, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere38_1.geometry}
      material={gltf.materials.White}
      position={[5.22, 8.81, 5.36]}
      rotation={[Math.PI, -0.77, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere39_1.geometry}
      material={gltf.materials.White}
      position={[5.74, 13.1, 4.79]}
      rotation={[Math.PI, -0.88, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere40_1.geometry}
      material={gltf.materials.White}
      position={[6.21, 13.56, 4.18]}
      rotation={[Math.PI, -0.98, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere41_1.geometry}
      material={gltf.materials.White}
      position={[6.6, 9.93, 3.52]}
      rotation={[Math.PI, -1.08, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere42_1.geometry}
      material={gltf.materials.White}
      position={[6.93, 4.31, 2.82]}
      rotation={[Math.PI, -1.18, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere43_1.geometry}
      material={gltf.materials.White}
      position={[7.18, -0.06, 2.09]}
      rotation={[Math.PI, -1.29, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere44_1.geometry}
      material={gltf.materials.White}
      position={[7.36, -0.65, 1.34]}
      rotation={[Math.PI, -1.39, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere45_1.geometry}
      material={gltf.materials.White}
      position={[7.46, 2.88, 0.58]}
      rotation={[Math.PI, -1.49, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere46_1.geometry}
      material={gltf.materials.White}
      position={[7.48, 8.49, -0.19]}
      rotation={[0, -1.55, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere47_1.geometry}
      material={gltf.materials.White}
      position={[7.42, 12.94, -0.96]}
      rotation={[0, -1.44, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere48_1.geometry}
      material={gltf.materials.White}
      position={[7.28, 13.65, -1.72]}
      rotation={[0, -1.34, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere49_1.geometry}
      material={gltf.materials.White}
      position={[7.06, 10.23, -2.46]}
      rotation={[0, -1.24, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere50_1.geometry}
      material={gltf.materials.White}
      position={[6.77, 4.63, -3.17]}
      rotation={[0, -1.13, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere51_1.geometry}
      material={gltf.materials.White}
      position={[6.41, 0.11, -3.85]}
      rotation={[0, -1.03, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere52_1.geometry}
      material={gltf.materials.White}
      position={[5.98, -0.74, -4.49]}
      rotation={[0, -0.93, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere53_1.geometry}
      material={gltf.materials.White}
      position={[5.49, 2.59, -5.08]}
      rotation={[0, -0.82, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere54_1.geometry}
      material={gltf.materials.White}
      position={[4.94, 8.16, -5.62]}
      rotation={[0, -0.72, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere55_1.geometry}
      material={gltf.materials.White}
      position={[4.33, 12.76, -6.1]}
      rotation={[0, -0.62, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere56_1.geometry}
      material={gltf.materials.White}
      position={[3.68, 13.73, -6.51]}
      rotation={[0, -0.52, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere57_1.geometry}
      material={gltf.materials.White}
      position={[3, 10.51, -6.85]}
      rotation={[0, -0.41, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere58_1.geometry}
      material={gltf.materials.White}
      position={[2.27, 4.96, -7.13]}
      rotation={[0, -0.31, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere59_1.geometry}
      material={gltf.materials.White}
      position={[1.53, 0.28, -7.32]}
      rotation={[0, -0.21, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere60_1.geometry}
      material={gltf.materials.White}
      position={[0.77, -0.81, -7.44]}
      rotation={[0, -0.1, 0]}
    />
    <T.Mesh geometry={gltf.nodes.Sphere61_1.geometry} material={gltf.materials.White} position={[0, 2.31, -7.48]} />
    <T.Mesh
      geometry={gltf.nodes.Sphere1_2.geometry}
      material={gltf.materials.White}
      position={[-0.49, 11.84, -3.74]}
      rotation={[0, 0.13, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere2_2.geometry}
      material={gltf.materials.White}
      position={[-0.98, 10.08, -3.64]}
      rotation={[0, 0.26, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere3_2.geometry}
      material={gltf.materials.White}
      position={[-1.44, -0.72, -3.48]}
      rotation={[0, Math.PI / 8, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere4_2.geometry}
      material={gltf.materials.White}
      position={[-1.88, 6.55, -3.26]}
      rotation={[0, Math.PI / 6, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere5_2.geometry}
      material={gltf.materials.White}
      position={[-2.3, 13.64, -2.99]}
      rotation={[0, 0.65, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere6_2.geometry}
      material={gltf.materials.White}
      position={[-2.67, 2.75, -2.67]}
      rotation={[0, Math.PI / 4, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere7_2.geometry}
      material={gltf.materials.White}
      position={[-2.99, 1.21, -2.3]}
      rotation={[0, 0.92, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere8_2.geometry}
      material={gltf.materials.White}
      position={[-3.26, 12.89, -1.88]}
      rotation={[0, Math.PI / 3, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere9_2.geometry}
      material={gltf.materials.White}
      position={[-3.48, 8.47, -1.44]}
      rotation={[0, 1.18, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere10_2.geometry}
      material={gltf.materials.White}
      position={[-3.64, -0.95, -0.98]}
      rotation={[0, 1.31, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere11_2.geometry}
      material={gltf.materials.White}
      position={[-3.74, 8.27, -0.49]}
      rotation={[0, 1.44, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere12_2.geometry}
      material={gltf.materials.White}
      position={[-3.77, 12.99, 0]}
      rotation={[0, 1.57, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere13_2.geometry}
      material={gltf.materials.White}
      position={[-3.74, 1.36, 0.49]}
      rotation={[-Math.PI, 1.44, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere14_2.geometry}
      material={gltf.materials.White}
      position={[-3.64, 2.57, 0.98]}
      rotation={[-Math.PI, 1.31, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere15_2.geometry}
      material={gltf.materials.White}
      position={[-3.48, 13.59, 1.44]}
      rotation={[-Math.PI, 1.18, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere16_2.geometry}
      material={gltf.materials.White}
      position={[-3.26, 6.76, 1.88]}
      rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere17_2.geometry}
      material={gltf.materials.White}
      position={[-2.99, -0.77, 2.3]}
      rotation={[-Math.PI, 0.92, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere18_2.geometry}
      material={gltf.materials.White}
      position={[-2.67, 9.9, 2.67]}
      rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere19_2.geometry}
      material={gltf.materials.White}
      position={[-2.3, 11.99, 2.99]}
      rotation={[-Math.PI, 0.65, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere20_2.geometry}
      material={gltf.materials.White}
      position={[-1.88, 0.25, 3.26]}
      rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere21_2.geometry}
      material={gltf.materials.White}
      position={[-1.44, 4.15, 3.48]}
      rotation={[-Math.PI, Math.PI / 8, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere22_2.geometry}
      material={gltf.materials.White}
      position={[-0.98, 13.89, 3.64]}
      rotation={[-Math.PI, 0.26, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere23_2.geometry}
      material={gltf.materials.White}
      position={[-0.49, 5.03, 3.74]}
      rotation={[-Math.PI, 0.13, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere24_2.geometry}
      material={gltf.materials.White}
      position={[0, -0.2, 3.77]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere25_2.geometry}
      material={gltf.materials.White}
      position={[0.49, 11.34, 3.74]}
      rotation={[Math.PI, -0.13, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere26_2.geometry}
      material={gltf.materials.White}
      position={[0.98, 10.68, 3.64]}
      rotation={[Math.PI, -0.26, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere27_2.geometry}
      material={gltf.materials.White}
      position={[1.44, -0.52, 3.48]}
      rotation={[Math.PI, -Math.PI / 8, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere28_2.geometry}
      material={gltf.materials.White}
      position={[1.88, 5.85, 3.26]}
      rotation={[Math.PI, -Math.PI / 6, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere29_2.geometry}
      material={gltf.materials.White}
      position={[2.3, 13.8, 2.99]}
      rotation={[Math.PI, -0.65, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere30_2.geometry}
      material={gltf.materials.White}
      position={[2.67, 3.37, 2.67]}
      rotation={[Math.PI, -Math.PI / 4, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere31_2.geometry}
      material={gltf.materials.White}
      position={[2.99, 0.74, 2.3]}
      rotation={[Math.PI, -0.92, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere32_2.geometry}
      material={gltf.materials.White}
      position={[3.26, 12.51, 1.88]}
      rotation={[Math.PI, -Math.PI / 3, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere33_2.geometry}
      material={gltf.materials.White}
      position={[3.48, 9.14, 1.44]}
      rotation={[Math.PI, -1.18, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere34_2.geometry}
      material={gltf.materials.White}
      position={[3.64, -0.91, 0.98]}
      rotation={[Math.PI, -1.31, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere35_2.geometry}
      material={gltf.materials.White}
      position={[3.74, 7.59, 0.49]}
      rotation={[Math.PI, -1.44, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere36_2.geometry}
      material={gltf.materials.White}
      position={[3.77, 13.3, 0]}
      rotation={[0, -1.57, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere37_2.geometry}
      material={gltf.materials.White}
      position={[3.74, 1.89, -0.49]}
      rotation={[0, -1.44, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere38_2.geometry}
      material={gltf.materials.White}
      position={[3.64, 2, -0.98]}
      rotation={[0, -1.31, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere39_2.geometry}
      material={gltf.materials.White}
      position={[3.48, 13.35, -1.44]}
      rotation={[0, -1.18, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere40_2.geometry}
      material={gltf.materials.White}
      position={[3.26, 7.46, -1.88]}
      rotation={[0, -Math.PI / 3, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere41_2.geometry}
      material={gltf.materials.White}
      position={[2.99, -0.89, -2.3]}
      rotation={[0, -0.92, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere42_2.geometry}
      material={gltf.materials.White}
      position={[2.67, 9.26, -2.67]}
      rotation={[0, -Math.PI / 4, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere43_2.geometry}
      material={gltf.materials.White}
      position={[2.3, 12.43, -2.99]}
      rotation={[0, -0.65, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere44_2.geometry}
      material={gltf.materials.White}
      position={[1.88, 0.66, -3.26]}
      rotation={[0, -Math.PI / 6, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere45_2.geometry}
      material={gltf.materials.White}
      position={[1.44, 3.49, -3.48]}
      rotation={[0, -Math.PI / 8, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere46_2.geometry}
      material={gltf.materials.White}
      position={[0.98, 13.82, -3.64]}
      rotation={[0, -0.26, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere47_2.geometry}
      material={gltf.materials.White}
      position={[0.49, 5.72, -3.74]}
      rotation={[0, -0.13, 0]}
    />
    <T.Mesh geometry={gltf.nodes.Sphere48_2.geometry} material={gltf.materials.White} position={[0, -0.47, -3.77]} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
